ForOneStep/OneStep-server

build.gradle
src/main/java/com/onestep/server/entity/Answer.java
src/main/java/com/onestep/server/entity/Comment.java
src/main/java/com/onestep/server/entity/Family.java
src/main/java/com/onestep/server/entity/Letter.java
src/main/java/com/onestep/server/entity/PhotoBook.java
src/main/java/com/onestep/server/entity/Question.java
src/main/java/com/onestep/server/entity/Quiz.java
src/main/java/com/onestep/server/entity/User.java
src/main/resources/application.properties

[#4] Feat: entity 생성

---

build.gradle
src/main/resources/application.properties

[#2]Setting: AWS, DB연결

---

build.gradle
src/main/java/com/onestep/server/controller/answer/AnswerController.java
src/main/java/com/onestep/server/entity/Answer.java
src/main/java/com/onestep/server/entity/ImageInfra/S3Config.java
src/main/java/com/onestep/server/entity/answer/AnswerDTO.java
src/main/java/com/onestep/server/repository/IAnswerRepository.java
src/main/java/com/onestep/server/service/answer/AnswerService.java
src/main/java/com/onestep/server/service/image/S3Uploader.java

[#13]Feat: 답변 Create API 생성

---

src/main/java/com/onestep/server/controller/letter/LetterController.java
src/main/java/com/onestep/server/entity/Letter.java
src/main/java/com/onestep/server/repository/ILetterRepository.java
src/main/java/com/onestep/server/service/letter/LetterService.java

resolved: #9, resolved: #11, resolved: #12

[#9 #11, #12]Feat: 익명쪽지 작성/목록 API 생성

---

src/main/java/com/onestep/server/controller/answer/AnswerController.java
src/main/java/com/onestep/server/entity/answer/AnswerReturnDTO.java
src/main/java/com/onestep/server/repository/IAnswerRepository.java
src/main/java/com/onestep/server/repository/IFamilyRepository.java
src/main/java/com/onestep/server/service/answer/AnswerService.java

[#14][#15]Feat: 가족 답변 확인, 답변 수정 API 생성

---

src/main/java/com/onestep/server/entity/Letter.java
src/main/java/com/onestep/server/entity/Question.java

[#33 #34]Fix: 이미지 답변 가능 여부/쪽지 공개 여부 확인 컬럼 추가

---

src/main/java/com/onestep/server/controller/letter/LetterController.java
src/main/java/com/onestep/server/entity/letter/LetterListDTO.java
src/main/java/com/onestep/server/repository/ILetterRepository.java
src/main/java/com/onestep/server/service/letter/LetterService.java

Feat: 이번주 공개된 쪽지 Read / 쪽지 공개 자동화

---

src/main/java/com/onestep/server/controller/question/QuestionController.java
src/main/java/com/onestep/server/repository/IQuestionRepository.java
src/main/java/com/onestep/server/service/question/QuestionService.java

[#39]Feat: 답변한 질문 목록 Read API 생성

---

src/main/java/com/onestep/server/controller/answer/AnswerController.java
src/main/java/com/onestep/server/entity/Answer.java
src/main/java/com/onestep/server/entity/LikeAnswer.java
src/main/java/com/onestep/server/entity/answer/AnswerDTO.java
src/main/java/com/onestep/server/entity/answer/AnswerReturnDTO.java
src/main/java/com/onestep/server/entity/like/LikeAnswerClass.java
src/main/java/com/onestep/server/entity/like/LikeAnswerDTO.java
src/main/java/com/onestep/server/repository/ILikeAnswerRepository.java
src/main/java/com/onestep/server/service/answer/AnswerService.java

[#17]Feat: 좋아요 등록/취소 API 생성

---

build.gradle
src/main/java/com/onestep/server/config/ServletConfig.java
src/main/java/com/onestep/server/config/SwaggerConfig.java

[#42]Feat: Swagger 연동

---

src/main/java/com/onestep/server/controller/comment/CommentController.java
src/main/java/com/onestep/server/entity/Comment.java
src/main/java/com/onestep/server/entity/comment/WriteCommentDto.java
src/main/java/com/onestep/server/repository/ICommentRepository.java
src/main/java/com/onestep/server/service/comment/CommentService.java

[#18] Feat: 댓글 작성 API 생성

---

src/main/java/com/onestep/server/controller/comment/CommentController.java
src/main/java/com/onestep/server/entity/Comment.java
src/main/java/com/onestep/server/entity/comment/ViewCommentDto.java
src/main/java/com/onestep/server/repository/ICommentRepository.java
src/main/java/com/onestep/server/service/comment/CommentService.java

[#19] Feat: 답변별 댓글 Read API 생성

---

src/main/java/com/onestep/server/entity/Answer.java
src/main/java/com/onestep/server/entity/GroupQuestion.java

[#48]Feat: gpt 연결에 따른 DB 구조 변경

---

.gitignore
src/main/java/com/onestep/server/entity/KeyWord.java
src/main/java/com/onestep/server/entity/Question.java
src/main/java/com/onestep/server/entity/gpt/ChatRequestDTO.java
src/main/java/com/onestep/server/entity/gpt/ChatResponseDTO.java
src/main/java/com/onestep/server/entity/gpt/MessageDTO.java
src/main/java/com/onestep/server/repository/IKeyWordRepository.java
src/main/java/com/onestep/server/service/question/GptService.java

Feat: GPT - Spring연결, 프롬프트 엔지니어링

---

src/main/java/com/onestep/server/controller/photoBook/PhotoBookController.java
src/main/java/com/onestep/server/entity/photoBook/photoBookDTO.java
src/main/java/com/onestep/server/repository/IPhotoBookRepository.java
src/main/java/com/onestep/server/service/photoBook/PhotoBookService.java

[#57] Feat: 사진첩 글 작성 API 생성

---

src/main/java/com/onestep/server/controller/photoBook/PhotoBookController.java
src/main/java/com/onestep/server/controller/photoBookComment/PhotoBookCommentController.java
src/main/java/com/onestep/server/entity/PhotoBook.java
src/main/java/com/onestep/server/entity/PhotoBookComment.java
src/main/java/com/onestep/server/entity/photoBook/PhotoBookDTO.java
src/main/java/com/onestep/server/entity/photoBook/ViewPhotoBookDTO.java
src/main/java/com/onestep/server/entity/photoBookComment/ViewPhotoBookCommentDTO.java
src/main/java/com/onestep/server/entity/photoBookComment/WritePhotoBookCommentDTO.java
src/main/java/com/onestep/server/repository/ICommentRepository.java
src/main/java/com/onestep/server/repository/IPhotoBookCommentRepository.java
src/main/java/com/onestep/server/repository/IPhotoBookRepository.java
src/main/java/com/onestep/server/service/photoBook/PhotoBookService.java
src/main/java/com/onestep/server/service/photoBookComment/PhotoBookCommentService.java

[#59] Feat:사진첩 글 리스트 확인 API 생성

---

src/main/java/com/onestep/server/controller/quiz/QuizController.java
src/main/java/com/onestep/server/entity/QuizAnswer.java
src/main/java/com/onestep/server/entity/quiz/QuizAnswerDTO.java
src/main/java/com/onestep/server/entity/quiz/QuizAnswerRequestDTO.java
src/main/java/com/onestep/server/entity/quiz/QuizDTO.java
src/main/java/com/onestep/server/repository/IFamilyRepository.java
src/main/java/com/onestep/server/repository/IQuizAnswerRepository.java
src/main/java/com/onestep/server/repository/IUserRepository.java
src/main/java/com/onestep/server/service/quiz/QuizService.java

퀴즈 등록 시 가족 구성원 quizAnswer db에 저장

Fix: 퀴즈 createAPI 로직 수정(오전 6시 이전 등록시 전날 날짜로 등록),

---

src/main/java/com/onestep/server/controller/answer/AnswerController.java
src/main/java/com/onestep/server/entity/Family.java
src/main/java/com/onestep/server/entity/answer/AnswerWithValidDTO.java
src/main/java/com/onestep/server/service/answer/AnswerService.java

[#44]Feat: 가족 구성원 전체 답변 여부 확인

---

src/main/java/com/onestep/server/ImageInfra/S3Config.java
src/main/java/com/onestep/server/controller/photoBook/PhotoBookController.java
src/main/java/com/onestep/server/repository/IPhotoBookCommentRepository.java
src/main/java/com/onestep/server/repository/IPhotoBookRepository.java
src/main/java/com/onestep/server/service/image/S3Uploader.java
src/main/java/com/onestep/server/service/photoBook/PhotoBookService.java

[#96]Feat: 사진첩 삭제 API 생성

---

src/main/java/com/onestep/server/controller/quiz/QuizController.java
src/main/java/com/onestep/server/repository/IQuizRepository.java
src/main/java/com/onestep/server/service/quiz/QuizService.java

[#101]Feat: 오늘자 퀴즈 확인API 생성
